defaults:
  - robot: panda_franky_interface_policy 
  - cams: camera_manager
  - _self_

hydra:
  searchpath:
    - file:///home/ceylanb/robot/robot_io/robot_io/conf

output_dir: /home/ceylanb/DreMa/drema_project/input
task_name_prefix: "task_"

calibration_file: /home/ceylanb/robot/robot_io/calibration/calibration_files/panda_realsenseD435_T_tcp_cam.npy

# "arch_parallel", "arch_skewed_clockwise", "arch_skewed_counterclockwise", "pose_sampler", "line_scan"
movement_type: "line_scan"  

line_scan:
  num_waypoints: 100
  start_point: [0.35, -0.40, 0.55] # X, Y, Z
  end_point:   [0.35,  0.30, 0.55] # X, Y, Z


movement:
  num_waypoints: 200
  flip_orientation: false
  arch_parallel:
    start_offset:  [0.0, -0.4, -0.1]  # X, Y, Z
    end_offset:    [0.0,  0.3, -0.1]  
    corner_offset: [-0.1, 0.0, 0.4]
  arch_skewed_counterclockwise:
    start_offset:  [0.1, -0.3, -0.1]  
    end_offset:    [-0.1, 0.3, -0.1]  
    corner_offset: [-0.1, 0.0, 0.4]
  arch_skewed_clockwise:
    start_offset:  [0.1, 0.3, -0.1]   
    end_offset:    [-0.1, -0.4, -0.1] 
    corner_offset: [-0.1, 0.0, 0.4]
pose_sampler:
    num_poses: 50
    # box limits
    z_limits: [0.55, 0.65]      # Z: 55cm to 65cm
    x_limits: [0.30, 0.40]      # X: 30cm to 40cm forward
    y_limits: [-0.40, 0.30]     # Y: -40cm to +30cm
    max_rotation_noise_deg: 15.0