data:
  # source_path: "/home/ceylanb/DreMa/drema_project/input/gold_data"
  source_path: "/home/gunnleif/Projects/drema/drema_project/input/gello_bottle1_rawtsdf"
  # source_path: "/home/gunnleif/Projects/drema/drema_project/input/gello_woodencube3_rawtsdf"
  
  # source_path: "/home/ceylanb/DreMa/drema_project/input/sample_data/slide_block_to_color_target_episode0_start"
  # source_path: "/home/gunnleif/Projects/drema_project/input/sample_data/put_groceries_in_cupboard_episode1_start"
  assets_directory: "output"
  assets_path: "${data.source_path}/${data.assets_directory}"
  trajectory_file: "${data.source_path}/dictionary.pkl"

defaults:
  - simulation: real_world_simulation
  - training: real_world_params_fixes


